#!/bin/bash
set -u
set -e
readonly DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

random_password() {
    < /dev/urandom tr -dc _A-Za-z0-9 | head -c${1:-32}; echo;
}

main() {
    local port=${1:-8080}; shift
    local password=${1:-$(random_password)}; shift
    local ip=$(curl -s http://whatismijnip.nl |cut -d " " -f 5)
    cat <<EOF
#########################################################
# http://$ip:$port
# TOMCAT_ADMIN_USER: admin
# TOMCAT_ADMIN_PASSWORD: $password
#########################################################
EOF
    docker run --rm -p $port:8080 -e TOMCAT_ADMIN_PASSWORD=$password islandora/claw-tomcat ash
}
main "$@"
